Repository askap-vast/vast-tools, pull requests merged in 2022-03, with the labels that each got.

#337 Fixed pandas append deprecation
  CHANGELOG.md
  tests/test_pipeline.py
  tests/test_query.py
  tests/test_source.py
  vasttools/pipeline.py
  vasttools/query.py
  vasttools/source.py
  vasttools/survey.py
  vasttools/tools.py
Labels: tests

#345 Correctly implement legend on lightcurve
  CHANGELOG.md
  vasttools/source.py
Labels: bug fix

#346 Add check for existence of requested data to Query init
  CHANGELOG.md
  tests/test_query.py
  vasttools/query.py
Labels: enhancement
